version: '3.8'

services:
  ffc-sfi-siti-agri-mock:
    build:
      context: .
      target: production
    image: ffc-sfi-siti-agri-mock
    container_name: ffc-sfi-siti-agri-mock
    environment: {}
