version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-sfi-siti-agri-mock:
    build:
      target: development
    image: ffc-sfi-siti-agri-mock-development
    container_name: ffc-sfi-siti-agri-mock-development
    ports:
      - "3002:3002"
      - "9231:9229"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
