{{- include "ffc-helm-library.container-config-map" (list . "ffc-sfi-siti-agri-mock.config-map") -}}
{{- define "ffc-sfi-siti-agri-mock.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  DELAY_IN_SECONDS: {{ quote .Values.container.delayInSeconds }}
{{- end -}}
