{{- include "ffc-helm-library.deployment" (list . "ffc-sfi-siti-agri-mock.deployment") -}}
{{- define "ffc-sfi-siti-agri-mock.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "ffc-helm-library.container" (list . "ffc-sfi-siti-agri-mock.container") }}
{{- end -}}
