environment: development
name: ffc-sfi-siti-agri-mock
namespace: ffc-sfi
workstream: ffc-sfi
image: ffc-sfi-siti-agri-mock

labels: {}

appInsights:
  key:

containerConfigMap:
  name: ffc-sfi-siti-agri-mock-config-map

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReadySeconds: 0

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 40Mi
  limitCpu: 40m
  port: 3002

livenessProbe:
  path: /healthz
  port: 3002
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3002
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
